"""empty message

Revision ID: 832994e2a31f
Revises: 92604cfc822c
Create Date: 2024-04-16 04:17:37.304739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832994e2a31f'
down_revision = '92604cfc822c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'picture', ['picture_id'], ['id'])

    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_constraint('picture_news_id_fkey', type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('picture_news_id_fkey', 'news', ['news_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('picture_id')

    # ### end Alembic commands ###
